### ISSUE TITLE
Work with img

### ISSUE THREAD

**Issue by DumDereDum** [DumDereDum/Magic-Piano#25]
Try to use the originally captured image instead of resized, and do resize after algorithm do all its work

**Comment by KimNikita** [comment]
it's unreal, because detector give us (x,y) on non-resized image and we check press on no-resized BUT we see and manipulate our hands on resized image

**Comment by DumDereDum** [comment]
@KimNikita check this branch 
https://github.com/DumDereDum/Magic-Piano/tree/draft
you are able to resize the image after all drawings.

use there the sizes of captured image 
https://github.com/DumDereDum/Magic-Piano/blob/main/src/main.py#L21

**Comment by KimNikita** [comment]
i think it can be closed)
